name: Deployment Workflow

on:
  push:
    branches: [ master ]

jobs:
  deploy_prod:
    if: contains( github.ref, 'master')
    runs-on: ubuntu-latest
    container: keymetrics/pm2:6
    steps:
      - uses: actions/checkout@master
      - name: "Update environment"
        run: apk update && apk upgrade
      - name: "Install git"
        run: apk add git openssh bash
      - name: "Start deployment"
        run: bash ./.github/deploy.sh
        env:
          TARGET_SERVER_HOST: ${{ secrets.TARGET_SERVER_HOST }}
          TARGET_SERVER_USER: ${{ secrets.TARGET_SERVER_USER }}
          TARGET_SERVER_SECRET_KEY_BASE64: ${{ secrets.TARGET_SERVER_SECRET_KEY_BASE64 }}
